services:
  db:
    image: postgres:17
    restart: no
    volumes:
      - db:/var/lib/postgresql/data
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: form-forge
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: "5s"
      timeout: "5s"
      retries: 5

  adminer:
    image: adminer:5
    restart: no
    depends_on:
      - db
    ports:
      - "8082:8080"

volumes:
  db: