services:
  db:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
      POSTGRES_DB: ${POSTGRES_DB:-form-forge}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-form-forge}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  rustfs:
    image: rustfs/rustfs:latest
    restart: unless-stopped
    environment:
      RUSTFS_ROOT_USER: ${S3_ACCESS_KEY:?S3_ACCESS_KEY is required}
      RUSTFS_ROOT_PASSWORD: ${S3_SECRET_KEY:?S3_SECRET_KEY is required}
      RUSTFS_VOLUMES: /data/rustfs0
      # Webhook notification for object deletions (lifecycle expiration)
      # Uses MinIO-compatible environment variable naming
      MINIO_NOTIFY_WEBHOOK_ENABLE_primary: "on"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_primary: "http://backend:8081/internal/s3-events"
    volumes:
      - rustfs_data:/data
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  createbuckets:
    image: quay.io/minio/mc:latest
    depends_on:
      rustfs:
        condition: service_healthy
    restart: "no"
    environment:
      S3_ACCESS_KEY: ${S3_ACCESS_KEY:?S3_ACCESS_KEY is required}
      S3_SECRET_KEY: ${S3_SECRET_KEY:?S3_SECRET_KEY is required}
      S3_BUCKET: ${S3_BUCKET:-form-forge}
    volumes:
      - ./config/lifecycle.json:/lifecycle.json:ro
    entrypoint: /bin/sh
    command:
      - -c
      - |
        /usr/bin/mc alias set rustfs http://rustfs:9000 "$${S3_ACCESS_KEY}" "$${S3_SECRET_KEY}"
        /usr/bin/mc mb --ignore-existing rustfs/$${S3_BUCKET}
        /usr/bin/mc ilm import rustfs/$${S3_BUCKET} < /lifecycle.json
        /usr/bin/mc event add rustfs/$${S3_BUCKET} arn:minio:sqs::primary:webhook --event delete || true
        echo "Bucket '$${S3_BUCKET}' initialized with lifecycle rules and webhook events"

  backend:
    build:
      context: ./apps/api
      dockerfile: ../../docker/api.Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      rustfs:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB:-form-forge}
      DB_MAX_CONNECTIONS: ${DB_MAX_CONNECTIONS:-5}
      BIND_ADDR: 0.0.0.0:8081
      RUST_LOG: ${RUST_LOG:-info}
      S3_ENDPOINT: http://rustfs:9000
      S3_PUBLIC_ENDPOINT: ${S3_PUBLIC_ENDPOINT:?S3_PUBLIC_ENDPOINT is required}
      S3_BUCKET: ${S3_BUCKET:-form-forge}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_REGION: ${S3_REGION:-us-east-1}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  frontend:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
      PORT: 3000
      HOSTNAME: 0.0.0.0
      API_URL: http://backend:8081
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://localhost:3000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})\" || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
      - rustfs
    ports:
      - "${HTTP_PORT:-80}:80"
    volumes:
      - ./docker/nginx.prod.conf:/etc/nginx/nginx.conf:ro

volumes:
  db_data:
  rustfs_data: