services:
  db:
    image: postgres:17
    restart: no
    # Use tmpfs for faster test execution (in-memory storage)
    tmpfs:
      - /var/lib/postgresql/data
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: form-forge
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: "5s"
      timeout: "5s"
      retries: 5