services:
  db:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-form-forge}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-form-forge}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  rustfs:
    image: rustfs/rustfs:latest
    restart: unless-stopped
    environment:
      RUSTFS_ACCESS_KEY: ${S3_ACCESS_KEY}
      RUSTFS_SECRET_KEY: ${S3_SECRET_KEY}
      RUSTFS_CONSOLE_ENABLE: ${S3_CONSOLE_ENABLE:-false}
      RUSTFS_VOLUMES: /data/rustfs0
      # Webhook notification for object deletions (lifecycle expiration)
      RUSTFS_NOTIFY_WEBHOOK_ENABLE_primary: "on"
      RUSTFS_NOTIFY_WEBHOOK_ENDPOINT_primary: "http://backend:8081/internal/s3-events"
      RUSTFS_NOTIFY_WEBHOOK_QUEUE_DIR_primary: "/data/rustfs0/.events"
      RUST_LOG: ${RUST_LOG:-info}
      RUST_BACKTRACE: 1
    volumes:
      - rustfs_data:/data
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  createbuckets:
    image: quay.io/minio/mc:latest
    depends_on:
      rustfs:
        condition: service_healthy
    restart: "no"
    environment:
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_REGION: ${S3_REGION:-eu-central}
      S3_BUCKET: ${S3_BUCKET:-form-forge}
    entrypoint: /bin/sh
    command:
      - -c
      - |
        /usr/bin/mc alias set rustfs http://rustfs:9000 "$${S3_ACCESS_KEY}" "$${S3_SECRET_KEY}"
        /usr/bin/mc mb --ignore-existing rustfs/$${S3_BUCKET}
        echo '{"Rules":[{"ID":"expire-sheets-1-days","Status":"Enabled","Filter":{"Prefix":"sheets/"},"Expiration":{"Days":1}}]}' | /usr/bin/mc ilm import rustfs/$${S3_BUCKET}
        /usr/bin/mc event remove rustfs/$${S3_BUCKET} --force || true
        /usr/bin/mc event add rustfs/$${S3_BUCKET} arn:rustfs:sqs:"$${S3_REGION}":primary:webhook --event delete || true
        echo "Bucket '$${S3_BUCKET}' initialized with lifecycle rules and webhook events"

  backend:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
      args:
        CARGO_FEATURES: json-logs,otel
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      rustfs:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB:-form-forge}
      DB_MAX_CONNECTIONS: ${DB_MAX_CONNECTIONS:-5}
      BIND_ADDR: 0.0.0.0:8081
      RUST_LOG: ${RUST_LOG:-info}
      RUST_BACKTRACE: 1
      S3_ENDPOINT: http://rustfs:9000
      S3_PUBLIC_ENDPOINT: ${S3_PUBLIC_ENDPOINT}
      S3_BUCKET: ${S3_BUCKET:-form-forge}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_REGION: ${S3_REGION:-eu-central}
      # OpenTelemetry (optional - set OTEL_EXPORTER_OTLP_ENDPOINT to enable)
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-}
      OTEL_SERVICE_NAME: ${OTEL_SERVICE_NAME:-form-forge-api}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  frontend:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
      PORT: 3000
      HOSTNAME: 0.0.0.0
      API_URL: http://backend:8081
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://localhost:3000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})\" || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  nginx:
    build:
      context: ./docker
      dockerfile: nginx.Dockerfile
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
      - rustfs
    expose:
      - "80"

volumes:
  db_data:
  rustfs_data:
